Adding practice questions for topic09.
University-of-Manitoba-Computer-Science/tools-n-techniques pull request #8
Opened 2024-01-30 00:01 UTC by ikaroruan

2024-01-30 15:08 UTC, fbristow requested changes
This overall looks great, thank you @ikaroruan!

You're overall aligning the assessment with the learning outcomes.

Please make the noted minor changes and this can be merged.

2024-01-30 15:08 UTC, fbristow commented on topic09/topic-8.md
> +In COMP 1002, you have successfully built your personal webpage. We are now
Please add a link to the topic where we did this.

2024-01-30 15:08 UTC, fbristow commented on topic09/topic-8.md
> +that you shared your script with a friend but he did not check your implementation.
Please do not use gendered pronouns to describe general people in English. Prefer instead to use "they" or "them". In this case, change this sentence to be

> Imagine that you shared your script with a friend but **they** did not...

2024-01-30 15:08 UTC, fbristow commented on topic09/topic-8.md
> +command. Otherwise, print "File found!" and execute the rest of the script.
Can you add either a reminder or a link back to the file operators?

2024-01-30 15:08 UTC, fbristow commented on topic09/topic-8.md
> +but not using a `for` loop?
This is an excellent challenge!

2024-01-30 15:08 UTC, fbristow commented on topic09/topic-8.md
> +then use `unzip` to extract the files from the compressed format.
Can you please prepare something for the practice, either:

1. Prepare a zip file containing a bunch of zip files, or
2. Write a little command that will _create_ a bunch of zip files.

2024-02-02 01:28 UTC, ikaroruan commented
Great! I have done the changes and it is now ready to be merged.

2024-02-06 20:43 UTC, merged